Script started on 2024-03-09 03:33:01+00:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="181" LINES="19"]
2024-03-09 03:33:02.594061: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-09 03:33:02.650781: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-09 03:33:02.651452: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-09 03:33:03.448718: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
TensorFlow version: 2.13.1
Available GPU devices: []
TensorFlow was built with CUDA support
Config: 16, 16, 16, 16, 16, 16
Iteration: 1/9375 - Iterations left: 9374
Training_accuracy:100.0
Testaccuracy:78.71000170707703
Config: 16, 16, 16, 16, 16, 32
Iteration: 2/9375 - Iterations left: 9373
^CTraceback (most recent call last):
  File "run.py", line 109, in <module>
    history = model.fit(X_train_padded, y_train, epochs=10, batch_size=2048, validation_data=(X_test_padded, y_test),verbose=0)
  File "/home/cyon/.local/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "/home/cyon/.local/lib/python3.8/site-packages/keras/src/engine/training.py", line 1742, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/cyon/.local/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/home/cyon/.local/lib/python3.8/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 825, in __call__
    result = self._call(*args, **kwds)
  File "/home/cyon/.local/lib/python3.8/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 890, in _call
    return self._no_variable_creation_fn(*args, **kwds)
  File "/home/cyon/.local/lib/python3.8/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 148, in __call__
    return concrete_function._call_flat(
  File "/home/cyon/.local/lib/python3.8/site-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py", line 1349, in _call_flat
    return self._build_call_outputs(self._inference_function(*args))
  File "/home/cyon/.local/lib/python3.8/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 196, in __call__
    outputs = self._bound_context.call_function(
  File "/home/cyon/.local/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 1457, in call_function
    outputs = execute.execute(
  File "/home/cyon/.local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
KeyboardInterrupt
^C
Script done on 2024-03-09 03:33:12+00:00 [COMMAND_EXIT_CODE="130"]
